-- Source: 20260618040000_add_website_monitors.sql
set local search_path = public;

create table if not exists website_monitors (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null,
  method text not null default 'GET',
  expected_status_min integer not null default 200,
  expected_status_max integer not null default 399,
  interval_sec integer not null default 120,
  timeout_sec integer not null default 10,
  grace_period_sec integer not null default 180,
  enabled boolean not null default true,
  hidden boolean not null default false,
  sort_order integer not null default 0,
  status text not null default 'pending',
  last_checked_at timestamptz,
  last_success_at timestamptz,
  last_failure_at timestamptz,
  last_status_code integer,
  last_raw_status_code integer,
  last_latency_ms integer,
  last_effective_reason text,
  last_error text,
  down_since timestamptz,
  last_notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint website_monitors_method_check check (method in ('GET', 'HEAD', 'TCP')),
  constraint website_monitors_status_check check (status in ('pending', 'up', 'down', 'paused')),
  constraint website_monitors_expected_status_check check (
    expected_status_min between 100 and 599
    and expected_status_max between 100 and 599
    and expected_status_min <= expected_status_max
  ),
  constraint website_monitors_interval_check check (interval_sec between 60 and 86400),
  constraint website_monitors_timeout_check check (timeout_sec between 1 and 30 and timeout_sec <= interval_sec),
  constraint website_monitors_grace_check check (grace_period_sec between 30 and 86400)
);

create table if not exists website_checks (
  id bigint generated by default as identity primary key,
  monitor_id bigint not null,
  checked_at timestamptz not null,
  ok boolean not null,
  effective_status text not null default 'down',
  effective_reason text,
  status_code integer,
  raw_status_code integer,
  latency_ms integer,
  error text,
  constraint website_checks_monitor_id_fkey foreign key (monitor_id) references website_monitors(id) on delete cascade
);

create index if not exists idx_website_monitors_sort_order on website_monitors(sort_order, id);
create index if not exists idx_website_monitors_due on website_monitors(enabled, last_checked_at, interval_sec);
create index if not exists idx_website_checks_monitor_time on website_checks(monitor_id, checked_at desc);

alter table public.website_monitors enable row level security;
alter table public.website_checks enable row level security;
alter table public.website_monitors force row level security;
alter table public.website_checks force row level security;

grant select, insert, update, delete on public.website_monitors to cf_monitor_app;
grant select, insert, update, delete on public.website_checks to cf_monitor_app;
grant usage on sequence website_monitors_id_seq to cf_monitor_app;
grant usage on sequence website_checks_id_seq to cf_monitor_app;

drop policy if exists cf_monitor_app_all on public.website_monitors;
create policy cf_monitor_app_all on public.website_monitors for all to cf_monitor_app using (true) with check (true);
drop policy if exists cf_monitor_app_all on public.website_checks;
create policy cf_monitor_app_all on public.website_checks for all to cf_monitor_app using (true) with check (true);

insert into settings (key, value)
values ('schema_bootstrap_version', 'postgres-2026-06-15-v16')
on conflict (key) do update set value = excluded.value;

-- -----------------------------------------------------------------------------

-- Source: 20260618050000_split_website_effective_and_raw_status.sql
set local search_path = public;

alter table website_monitors
  add column if not exists last_raw_status_code integer,
  add column if not exists last_effective_reason text;

alter table website_checks
  add column if not exists effective_status text not null default 'down',
  add column if not exists effective_reason text,
  add column if not exists raw_status_code integer;

update website_monitors
set last_raw_status_code = last_status_code
where last_raw_status_code is null
  and last_status_code is not null;

update website_monitors
set last_effective_reason = case
  when status = 'up' and last_error is null and last_status_code in (401, 403, 405, 412, 429) then 'reachable_challenge'
  when status = 'up' and last_error is null and last_status_code is not null then 'status_in_expected_range'
  when status = 'down' and last_error is not null then last_error
  else last_effective_reason
end
where last_effective_reason is null;

update website_checks
set effective_status = case when ok then 'up' else 'down' end,
    effective_reason = coalesce(effective_reason, case
      when ok and error is null and status_code in (401, 403, 405, 412, 429) then 'reachable_challenge'
      when ok and error is null then 'status_in_expected_range'
      when not ok and error is not null then error
      else 'unknown'
    end),
    raw_status_code = coalesce(raw_status_code, status_code);

insert into settings (key, value)
values ('schema_bootstrap_version', 'postgres-2026-06-15-v17')
on conflict (key) do update set value = excluded.value;

-- -----------------------------------------------------------------------------

-- Source: 20260618060000_set_website_monitor_default_interval.sql
set local search_path = public;

alter table website_monitors
  alter column interval_sec set default 120;

insert into settings (key, value)
values ('schema_bootstrap_version', 'postgres-2026-06-15-v18')
on conflict (key) do update set value = excluded.value;

-- -----------------------------------------------------------------------------

-- Source: 20260619090000_add_theme_management.sql
set local search_path = public;

create table if not exists themes (
  short text primary key,
  name text not null,
  description text not null default '',
  version text not null default '',
  author text not null default '',
  url text not null default '',
  preview_path text not null default '',
  style_path text not null,
  manifest_json text not null,
  config_json text not null default '{}',
  custom_css text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint themes_short_check check (short ~ '^[A-Za-z0-9_-]+$' and short <> 'default')
);

create table if not exists theme_assets (
  theme_short text not null,
  path text not null,
  content_type text not null,
  content_base64 text not null,
  size_bytes integer not null,
  created_at timestamptz not null default now(),
  constraint theme_assets_theme_short_fkey foreign key (theme_short) references themes(short) on delete cascade,
  primary key (theme_short, path)
);

insert into settings (key, value)
values ('active_theme', 'monitor')
on conflict (key) do nothing;

alter table public.themes enable row level security;
alter table public.theme_assets enable row level security;
alter table public.themes force row level security;
alter table public.theme_assets force row level security;

grant select, insert, update, delete on public.themes to cf_monitor_app;
grant select, insert, update, delete on public.theme_assets to cf_monitor_app;

drop policy if exists cf_monitor_app_all on public.themes;
create policy cf_monitor_app_all on public.themes for all to cf_monitor_app using (true) with check (true);
drop policy if exists cf_monitor_app_all on public.theme_assets;
create policy cf_monitor_app_all on public.theme_assets for all to cf_monitor_app using (true) with check (true);

insert into settings (key, value)
values ('schema_bootstrap_version', 'postgres-2026-06-15-v19')
on conflict (key) do update set value = excluded.value;

-- -----------------------------------------------------------------------------

-- Source: 20260621120000_allow_tcp_website_monitors.sql
set local search_path = public;

alter table website_monitors drop constraint if exists website_monitors_method_check;
alter table website_monitors add constraint website_monitors_method_check check (method in ('GET', 'HEAD', 'TCP'));

insert into settings (key, value)
values ('schema_bootstrap_version', 'postgres-2026-06-15-v20')
on conflict (key) do update set value = excluded.value;

-- -----------------------------------------------------------------------------

-- Source: 20260621130000_reapply_tcp_website_monitor_constraint.sql
set local search_path = public;

alter table website_monitors drop constraint if exists website_monitors_method_check;
alter table website_monitors add constraint website_monitors_method_check check (method in ('GET', 'HEAD', 'TCP'));

insert into settings (key, value)
values ('schema_bootstrap_version', 'postgres-2026-06-15-v21')
on conflict (key) do update set value = excluded.value;

-- -----------------------------------------------------------------------------

-- Source: 20260701000000_persist_agent_install_token.sql
set local search_path = public;

create or replace function public.cfm_create_client(input_client jsonb)
returns jsonb
language sql
set search_path = public
as $$
  insert into clients (uuid, token, token_hash, token_rotated_at, name, sort_order)
  values (
    coalesce(nullif(input_client->>'uuid', ''), gen_random_uuid()::text),
    nullif(input_client->>'token', ''),
    input_client->>'token_hash',
    now(),
    coalesce(input_client->>'name', ''),
    coalesce((input_client->>'sort_order')::integer, (select coalesce(max(sort_order), 0) + 1 from clients))
  )
  returning to_jsonb(clients);
$$;

create or replace function public.cfm_rotate_client_token(input_uuid text, input_token text, input_token_hash text)
returns jsonb
language sql
set search_path = public
as $$
  update clients
  set token = input_token,
      token_hash = input_token_hash,
      token_last_used_at = null,
      token_last_used_ip = '',
      token_rotated_at = now(),
      updated_at = now()
  where uuid = input_uuid
  returning to_jsonb(clients);
$$;

drop function if exists public.cfm_rotate_client_token(text, text);
drop function if exists public.cfm_set_client_install_token(text, text);

revoke all on function public.cfm_create_client(jsonb) from public;
revoke all on function public.cfm_create_client(jsonb) from anon;
revoke all on function public.cfm_create_client(jsonb) from authenticated;
grant execute on function public.cfm_create_client(jsonb) to service_role;

revoke all on function public.cfm_rotate_client_token(text, text, text) from public;
revoke all on function public.cfm_rotate_client_token(text, text, text) from anon;
revoke all on function public.cfm_rotate_client_token(text, text, text) from authenticated;
grant execute on function public.cfm_rotate_client_token(text, text, text) to service_role;

notify pgrst, 'reload schema';
